version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=socially
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306

  app:
    image: socially1.0:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/socially
    depends_on:
      - docker-mysql
    links:
      - docker-mysql